---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipe"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-isONclust2.git"

## Pipeline-specific parameters:
cores: 20

# cDNA or direct RNA reads in fastq format
reads_fastq: "evaluation/data/SIRV_PSC109_phmm_fl.fq"

# The path above is a directory, find and concatenate fastq files:
concatenate: true

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: true

# Options passed to pychopper:
pychopper_opts: ""

# Batch size in kilobases (if -1 then it is calculated based on the number of cores and bases):
batch_size: -1

# Maximum sequences per input batch (-1 means no limit):
batch_max_seq: -1

# Clustering mode:
cls_mode: "sahlin"

# Kmer size:
kmer_size: 11

# Window size:
window_size: 15

# Minimum cluser size in the left batch:
min_left_cls: 2

# Consensus period (-1 means no consensus):
consensus_period: -1

# Minimum number of minimizers shared between read and cluster:
min_shared: 5

# Minimum average quality value:
min_qual: 7.0

# Minmum mapped fraction of read to be included in cluster:
mapped_threshold: 0.7

# Minimum aligned fraction of read to be included in cluster:
aligned_threshold: 0.4

# Minimum fraction of minimizers shared compared to best hit, in order to continue mapping:
min_fraction: 0.8

# Minimum probability for i consecutive minimizers to be different between read and representative:
min_prob_no_hits: 0.1 
